# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
- repo: https://github.com/astral-sh/ruff-pre-commit # the ruff linter and formatter for python
  rev: v0.7.1
  hooks:
    - id: ruff # Run linter
      args: [ --fix ] # To enable lint fixes for pep8
    - id: ruff
      args: ["check", "--select", "I", "--fix"]
    - id: ruff-format # Run formatter
- repo: https://github.com/pre-commit/mirrors-mypy # For type hints
  rev: v1.13.0
  hooks:
    - id: mypy
      args:
        - --non-interactive
        - --install-types
        - --check-untyped-defs
        - --ignore-missing-imports
      exclude: ^tests/
      additional_dependencies: ['types-PyYAML']
